name: build

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.bbcode"
      - LICENSE
    branches: [main, dev]
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.bbcode"
      - LICENSE
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install build dependencies (apt)
        run: sudo apt install -y libx11-dev libxcursor-dev libpng-dev
        continue-on-error: false

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Caching yarn packages
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set Up NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Caching pip packages
        uses: actions/cache@v2
        id: pip-cache # use this to check for `cache-hit` (`steps.pip-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Generating `XCursor-Pro` Cursor Theme
        run: make
        continue-on-error: false

      - name: Compressing UNIX theme
        run: |
          tar -cvzf XCursor-Pro-Dark.tar.gz themes/XCursor-Pro-Dark
          tar -cvzf XCursor-Pro-Light.tar.gz themes/XCursor-Pro-Light
          tar -cvzf XCursor-Pro-Red.tar.gz themes/XCursor-Pro-Red

      - name: Uploading `bitmaps` artifact
        uses: actions/upload-artifact@v2
        with:
          name: bitmaps
          path: bitmaps/*

      - name: Uploading `XCursor-Pro-Dark` UNIX Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: XCursor-Pro-Dark
          path: XCursor-Pro-Dark.tar.gz

      - name: Uploading `XCursor-Pro-Light` UNIX Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: XCursor-Pro-Light
          path: XCursor-Pro-Light.tar.gz

      - name: Uploading `XCursor-Pro-Red` UNIX Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: XCursor-Pro-Red
          path: XCursor-Pro-Red.tar.gz

      - name: Uploading `XCursor-Pro-Dark` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: XCursor-Pro-Dark-Windows
          path: themes/XCursor-Pro-Dark-Windows/*

      - name: Uploading `XCursor-Pro-Light` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: XCursor-Pro-Light-Windows
          path: themes/XCursor-Pro-Light-Windows/*

      - name: Uploading `XCursor-Pro-Red` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: XCursor-Pro-Red-Windows
          path: themes/XCursor-Pro-Red-Windows/*
